server:
  port: 8000

spring:
  application:
    name: shortlink-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.197.138:8848
    gateway:
      routes:
        - id: shortlink-admin
          uri: lb://shortlink-admin/api/shortlink/admin/**
          predicates:
            - Path=/api/shortlink/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username

        - id: shortlink-project
          uri: lb://shortlink-project/api/shortlink/**
          predicates:
            - Path=/api/shortlink/**
          filters:
            - name: TokenValidate
  data:
    redis:
      host: 192.168.197.138
      port: 6379
      password: enshine