server:
  port: 8001

spring:
  application:
    name: shortlink-project
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.197.138:8848
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.197.138
      port: 6379
      password: enshine

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml
